#
# Module manifest for module 'OneStreamLabDeploy'
#
# Generated by: Rob Delve
#
# Generated on: 22/08/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'OneStreamLabDeploy.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = 'a3d6f0f1-6d8b-4f9e-a19a-4e6f7b1d3a0e'

# Author of this module
Author = 'Rob Delve'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2025 Rob Delve. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell DSC module for building and configuring OneStream XF lab environments.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @(
    'Start-OSLabBuild',
    'New-OSLabVmImage'
)

# DSC resources to export from this module
DscResourcesToExport = @(
    'OSLab_WebServer',
    'OSLab_DatabaseServer',
    'OSLab_OneStreamAppServer'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('OneStream', 'DSC', 'Automation', 'Lab')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/robdelve/oslabbuildconfig/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/robdelve/oslabbuildconfig'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
